# Generated by Django 5.2.1 on 2025-05-15 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('facilityId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HealthSupervisor',
            fields=[
                ('supervisorId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocalOfficer',
            fields=[
                ('officerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('condition', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.doctor')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.localofficer')),
            ],
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('reportDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.healthsupervisor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.patient')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.region')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('streetId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('totalPopulation', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.district')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.street'),
        ),
        migrations.AddField(
            model_name='localofficer',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.street'),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycholera.street'),
        ),
    ]
